---
apiVersion: v1
kind: Service
metadata:
  name: pa8729-test-service
  labels:
    username: pa8729
    env: test
spec:
  type: ClusterIP
  selector:
    app: pa8729-redis-test
  ports:
  - name: pa8729-redis-test
    port: 6379
    targetPort: 6379