---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa8729-test-redis-deployment
  labels:
    username: pa8729
    env: test
    app: pa8729-test-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pa8729-test-redis
  template:
    metadata:
      labels:
        username: pa8729
        env: test
        app: pa8729-test-redis
    spec:
      containers:
        - name: pa8729-test-redis
          image: redis:7
          volumeMounts:
            - name: pa8729-test-pvc
              mountPath: '/data'
      volumes:
        - name: pa8729-test-pvc
          persistentVolumeClaim:
            claimName: pa8729-test-pvc